import '../Styles/globals.css'
import Bg from './Components/Bg'
import Nav from './Components/Nav'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        <Nav />
        <Bg />
        {children}
      </body>
    </html>
  )
}
